//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

use serde::{Deserialize, Serialize};  //手动添加

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq,Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub username: String,
    #[sea_orm(unique)]
    pub telephone: i64,
    pub nickname: String,
    pub salt: String,
    pub password: String,
    pub gender: String,
    pub status:i64,
    pub create_time: Option<DateTimeUtc>,
    pub update_time: Option<DateTimeUtc>,
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
